name: Release to AWS

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy Task Tracker API
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 751424356366.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPO_NAME: task-tracker-api
      IMAGE_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
         docker buildx build \
            --platform linux/amd64 \
            --tag $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG \
            --output type=docker \
            --push .



      - name: Tag image for ECR
        run: |
          docker tag $ECR_REPO_NAME:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:$IMAGE_TAG

      - name: Push image to Amazon ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO_NAME:$IMAGE_TAG

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image for Docker Hub
        run: |
          docker tag $ECR_REPO_NAME:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$ECR_REPO_NAME:$IMAGE_TAG

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$ECR_REPO_NAME:$IMAGE_TAG

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./iac

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./iac

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./iac


